### ISSUE TITLE
Starting over to fix migration, can't get preset-typescript to work

### ISSUE THREAD

**Issue by mattfelten** [storybookjs/presets#51]
I've been having a lot of trouble updating Storybook from 5.1.9 to 5.2.5 and part of that is the Typescript setup we have. I threw my hands up and started an entire new project to at least get a build working, and then I can integrate it into my existing project. Even that doesn't work.

Basic example
https://github.com/mattfelten/storybook-preset-typescript-test

The one story here is not being found. I followed the docs. What am I missing?

**Comment by shilman** [comment]
Your config:
> configure(require.context('../stories', true, /\.stories\.tsx$/), module);

Your story file: `Test.story.tsx`

Once I rename to `Test.stories.tsx` it tries to load, but fails because there is more setup to do.

Storybook is meant to be added to an existing working app, not bootstrapped in an empty directory. To get it working I also needed to `yarn add typescript --dev` and create a `tsconfig.json`.

**Comment by mattfelten** [comment]
Gotcha. I'll keep working on this. I know this isn't the correct way of setting it up, but I'm having trouble with some dependencies (https://github.com/storybookjs/storybook/issues/8730) so just trying to isolate whether it's our project or I'm misconfiguring something.

**Comment by mattfelten** [comment]
Got it working. Thanks for your help!
