### ISSUE TITLE
@storybook/preset-create-react-app: babel-preset-react-app is require?

### ISSUE THREAD

**Issue by josias-r** [storybookjs/presets#86]
I got an error when updating to storybook v5.3 and the new @storybook/preset-create-react-app.
Apparently babel-preset-react-app was missing and I had to install it.

If this package is a requirement for this preset to work, why isn't it listed as a peer dependency or similar? 🤔

**Comment by vlaja** [comment]
This is actually mentioned here: https://storybook.js.org/docs/configurations/typescript-config/

It lists the requirement for adding  `babel-preset-react-app` and webpackFinal prop inside main.js, but it is easily overlooked.

**Comment by mrmckeb** [comment]
Hi @josias-r, this is quite strange - as if you have react-scripts installed, you must also have that preset installed. Can you provide a reproduction repo?

@vlaja that is actually a little confusing, the example you're referring to is for setting up TypeScript with CRA if you're not using this preset.
![image](https://user-images.githubusercontent.com/5043083/73438911-7907ee00-4357-11ea-9a90-e99820865367.png)

**Comment by vlaja** [comment]
@mrmckeb You might be true on that one. 

On the project where I tested, a have a bit of a hybrid config, with unejected react-scripts, but actually a non-standard library structure inside the src folder, as I'm using storybook directly for dev env, instead of CRA start.

I'm willing to try to set up a fresh CRA app with this preset included and see if it is working for me, or I still need to do some changes, and for what reason.

**Comment by mrmckeb** [comment]
That would be great, please give any feedback you have - we want to make presets great, and the CRA preset is by far the most popular.

**Comment by vlaja** [comment]
Tested the preset with the latest CRA with the base template and the typescript one.

**JS CRA**

1. `npx create-react-app storybook-preset-test`

This bootstraps the latest CRA app with the following package versions:

```
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0"
```

2. `npx -p @storybook/cli sb init`

The following devDependencies are installed:

```
  "devDependencies": {
    "@storybook/addon-actions": "^5.3.9",
    "@storybook/addon-links": "^5.3.9",
    "@storybook/addons": "^5.3.9",
    "@storybook/preset-create-react-app": "^1.5.2",
    "@storybook/react": "^5.3.9"
  }
```

3. added a test component as `src/components/TestComponent.js(x)` and imported to story
4. yarn storybook

Observed behaviour: Works as intended with both `.js` and `.jsx` extensions.

**TS CRA**

1. `npx create-react-app storybook-preset-test --template typescript`

This bootstraps the latest CRA app with the following package versions:

```
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0",
    "typescript": "~3.7.2"
```

2. `npx -p @storybook/cli sb init`

The following devDependencies are installed:

```
  "devDependencies": {
    "@storybook/addon-actions": "^5.3.9",
    "@storybook/addon-links": "^5.3.9",
    "@storybook/addons": "^5.3.9",
    "@storybook/preset-create-react-app": "^1.5.2",
    "@storybook/react": "^5.3.9"
  }
```

3. added a test component as `src/components/TestComponent.tsx` and imported to story
4. yarn storybook

Observed behaviour: 
- Works as intended with `.tsx` components
- Doesn't work with '.ts' components, which is ok as `.tsx` is required by default to correctly infer react JSX.Elements
- Stories need to remain in `.js`or `.jsx`format in order for stories to actually load, although the UI doesn't break, and project compiles normally.

@mrmckeb  I would personally say this works as intended, so the issue seems to be with the project setup.

@josias-r can you post more info about the error you are getting and your versions of `react`, `react-scripts` and all `storybook` packages?

**Comment by vlaja** [comment]
As a separate comment, I would personally expect the preset, when used with TypeScript CRA config which is widely used to behave differently:

- create default stories in `.tsx` format.
- register '.ts' and '.tsx' extensions with your webpack config

The current situation, unfortunately, allows users to import a TypeScript component, and pass wrong props as opposed to the definition inside an interface.

While you can see the required props in the editor, there is no automatic linting applied (vscode).

I would say that in the TS scenario, things simply work best if it is all is written TS, and I'm personally confused whether it is intended for the preset to support templates or not.

To avoid maintenance issues of the core CRA preset, my suggestion is to maybe create separate presets for templates such as the typescript and simply update the CLI to load them on storybook init.

**Comment by josias-r** [comment]
@vlaja I have now removed the babel-preset-react-app again to try to create a reproduction. Unfortunately, I don't get the error anymore :/
I've updated pretty much all the packages that could have had an influence on this since then (storybook, react-scripts, babel/core, etc.) but only minor versions. I tried rolling back the react-scripts version though, so that was not the cause of the issue. Anyways, I can now see the preset in the package-lock.
I guess the issue is now magically resolved, sorry for stealing your time!

**Comment by josias-r** [comment]
💡It just hit me, that I have an error sometimes when working on a project with a team (w/ git) it can happen that when someone resets the package-lock file and I pull those changes & even run `npm i` but without deleting the node_modules folder I get an error too saying that `babel-preset-react-app` was not found in node_modules, even though it should be in there.

Maybe because the way storybook logs error it displayed it differently than I usually see that error and I thought it was a storybook related bug.

Anyways if anyone stumbles across this issue, try to delete node_modules first. 😉
